on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      comment-id:
        required: true
        type: string
      file:
        required: true
        type: string
      network:
        required: true
        type: string
      fn:
        required: true
        type: string
      send:
        required: true
        type: string
      pull_request_number:
        required: true
        type: string
      delete-branch-after-send:
        required: true
        type: string
      group_telegram_chat_id:
        required: false
        default: ''
        type: string
      announcement_telegram_chat_id:
        required: false
        default: false
        type: string
      failure_telegram_chat_id:
        required: false
        default: ''
        type: string
      runs_on:
        required: true
        type: string
      compiler_cache_version:
        required: false
        default: 'v0.0.1'
        type: string
      brownie_cache_version:
        required: false
        type: string
        default: 'v0.0.1'
      close_pr:
        required: false
        default: 'false'
        type: string
      check_reviews:
        required: false
        default: 'false'
        type: string
      cached_runner:
        required: false
        default: 'false'
        type: string
      be:
        required: false
        default: 'false'
        type: string
      from_pr:
        required: false
        default: 'true'
        type: string
      job_description:
        required: false
        default: 'default cronjob description'
        type: string
      job_author:
        required: false
        type: string
        default: 'no cron job author specified'
    secrets:
      COORDINAPE_BEARER_TOKEN:
        required: false
      TELEGRAM_TOKEN:
        required: true
      POLYGONSCAN_TOKEN:
        required: true
      FTMSCAN_TOKEN:
        required: true
      ETHERSCAN_TOKEN:
        required: true
      BSCSCAN_TOKEN:
        required: true
      ARBISCAN_TOKEN:
        required: true
      SNOWTRACE_TOKEN:
        required: true
      PRIVATE_KEY:
        required: true
      PAT:
        required: true

jobs:
  roboanimalsWorkflow:
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: 60
    steps:
    - uses: hmarr/debug-action@v2
    - name: Create URL to the run output
      id: vars
      run: echo ::set-output name=run-url::https://github.com/${{github.repository}}/actions/runs/$GITHUB_RUN_ID

    - name: Save runner name
      id: runner_name
      run: echo ::set-output name=runner_name::$RUNNER_NAME
      
    - name: Edit comment with link to run
      if: ${{ inputs.from_pr == 'true' }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        body: |
          > ðŸš€ Agent ${{steps.runner_name.outputs.runner_name }} has picked up this request, follow progress [here](${{ steps.vars.outputs.run-url }})
          >

    - name: Checking out code
      uses: actions/checkout@v1
      with:
        ref: ${{ inputs.ref }}
        submodules: 'true'

    - name: Get PR title
      uses: actions/github-script@v3
      if: ${{ inputs.from_pr == 'true' }}
      id: get-pr-title
      with:
        script: |
          const {data: pull} = await github.pulls.get({...context.repo, pull_number: ${{ inputs.pull_request_number }}});
          if (!pull.title) {
            return 'Empty Title ðŸ¤¡';
          }
          return pull.title.replace(/\$/g, 'ðŸ’²');

    - name: Get PR body
      uses: actions/github-script@v3
      if: ${{ inputs.from_pr == 'true' }}
      id: get-pr-body
      with:
        script: |
          const {data: pull} = await github.pulls.get({...context.repo, pull_number: ${{ inputs.pull_request_number }}});
          if (!pull.body) {
            return 'Empty Description ðŸ¤¡';
          }
          return pull.body.replace(/\r\n/g, ' ðŸ¶ ').replace(/\$/g, 'ðŸ’²');


    - name: Get PR author
      uses: actions/github-script@v3
      if: ${{ inputs.from_pr == 'true' }}
      id: get-pr-author
      with:
        script: |
          const {data: pull} = await github.pulls.get({...context.repo, pull_number: ${{ inputs.pull_request_number }}});
          if (pull.user.login === null) {
            return 'Empty Author ðŸ¤¡';
          }
          return pull.user.login;

    - name: Pull down reviews
      uses: actions/github-script@v3
      if: ${{ inputs.check_reviews == 'true' }}
      id: get-pr
      with:
        script: |
          const { data: reviews } = await github.pulls.listReviews({
            ...context.repo,
            pull_number: ${{ inputs.pull_request_number }},
          })

          const approvals = reviews.filter(review => review.state == 'APPROVED')
          const reviews_filtered = approvals.filter(review => review.user.login != ${{ steps.get-pr-author.outputs.result }})
          core.info(`List of reviews:\n ${JSON.stringify(reviews_filtered)}`)
          return reviews_filtered.length

    - name: Check Reviews
      if: ${{ inputs.check_reviews == 'true' && inputs.send  == 'true' && steps.get-pr.outputs.result < 1}}
      run: exit 1

    - name: Fail on no reviews
      if: ${{ inputs.check_reviews == 'true' && failure() }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        body: |
          > Review requirement failed. Get at least one approval before sending.

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install ganache
      run: npm install -g ganache-cli@6.12.2

    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements-dev.txt -f https://pypi.org/project/multisig-ci

    - name: Grab lock message
      if: ${{ inputs.from_pr == 'true' && inputs.send == 'true'  }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        body: |
          > ðŸ”“ Grabbing lock for ${{ inputs.network }}.... Taking too long? [Read this.](https://github.com/yearn/yearn-workflows/tree/master#stuck-on-grabbing-lock)

    - name: Lock on send=true to avoid nonce race condition
      if: ${{ inputs.send  == 'true' }}
      uses: shogo82148/actions-mutex@v1
      with:
        key: send-${{ inputs.network }}

    - name: Grabbed lock message
      if: ${{ inputs.from_pr == 'true' && inputs.send == 'true'  }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        body: |
          > ðŸ” Successfully grabbed lock for ${{ inputs.network }}
          >
    
    - name: Add network config
      timeout-minutes: 1
      run: |
        brownie networks list true
        cp network-config.yaml ~/.brownie/
        brownie networks list true

    - name: Brownie compile
      if: ${{ inputs.fn != 'hydate_compiler_cache' }}
      run: |
        brownie compile

    - name: Run Function
      id: fn
      timeout-minutes: 45
      env:
        COORDINAPE_BEARER_TOKEN: ${{ secrets.COORDINAPE_BEARER_TOKEN }}
        POLYGONSCAN_TOKEN: ${{ secrets.POLYGONSCAN_TOKEN }}
        FTMSCAN_TOKEN: ${{ secrets.FTMSCAN_TOKEN }}
        ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
        BSCSCAN_TOKEN: ${{ secrets.BSCSCAN_TOKEN }}
        ARBISCAN_TOKEN: ${{ secrets.ARBISCAN_TOKEN }}
        SNOWTRACE_TOKEN: ${{ secrets.SNOWTRACE_TOKEN }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        GITHUB_ACTION_SEND: ${{ inputs.send }}
        BE: ${{ inputs.be }}
      run: |
        python3 -m multisig_ci brownie run ${{ inputs.file }} ${{ inputs.fn }} --network ${{ inputs.network }}-main-fork 1>output.txt 2>error.txt || EXIT_CODE=$?
        echo "::set-output name=brownie-exit-code::$EXIT_CODE"
        echo "::group:: Output"
        cat output.txt
        echo "::endgroup::"
        echo "::group:: Error"
        cat error.txt
        echo "::endgroup::"
        exit 0

    - name: Set timeout
      if: failure()
      id: timeout
      run: |
        echo "::group:: Output"
        cat output.txt
        echo "::endgroup::"
        echo "::group:: Error"
        cat error.txt
        echo "::endgroup::"
        echo "::set-output name=brownie-timeout::true"

    - name: Check failure
      id: failcheck
      run: |
        echo "::group:: Output"
        cat output.txt
        echo "::endgroup::"
        echo "::group:: Error"
        cat error.txt
        echo "::endgroup::"
        exit ${{ steps.fn.outputs.brownie-exit-code}}

    - name: Nonce fail check, add comment
      if: inputs.send == 'true' && env.NONCE == ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        body: |
          > Did not find nonce.txt. Did you run with send=true without actually posting the transaction at the end of your function? Use the @sign decorator above your function.

    - name: New TX Telegram Alert - MultiSig Chat
      env:
        TELEGRAM_MESSAGE: "Oof, ${{ steps.get-pr-author.outputs.result }} just tried to send a transaction without putting the @sign decorator above the function... Please join me in shaming this ðŸ¤¡"
      if: inputs.send == 'true' && env.NONCE == ''
      run: |
        python3 -m multisig_ci send_and_pin_message ${{ secrets.TELEGRAM_TOKEN }} ${{ inputs.group_telegram_chat_id }}
      continue-on-error: true

    - name: Nonce fail check
      if: inputs.send == 'true' && env.NONCE == ''
      run: |
        exit 1

    - name: Safe url check, add comment
      if: inputs.send == 'true' && env.SAFE_LINK == ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        body: |
          > Fatal error. Did not find safe.txt.

    - name: Safe fail check, add comment
      if: inputs.send == 'true' && env.SAFE_LINK == ''
      run: |
        exit 1

    - name: Fix ansi codes
      if: always() && inputs.from_pr == 'true'
      run: |
        sed -i 's/\x1b\[[0-9;]*m//g' ./error.txt
        sed -i 's/\x1b\[[0-9;]*m//g' ./output.txt

    - name: Read error.txt
      if: always() && inputs.from_pr == 'true'
      id: read_error
      uses: juliangruber/read-file-action@v1
      with:
        path: ./error.txt

    - name: Read output.txt
      if: always() && inputs.from_pr == 'true'
      id: read_output
      uses: juliangruber/read-file-action@v1
      with:
        path: ./output.txt
      
    - name: Edit comment with error message
      if: ${{ failure() && inputs.from_pr == 'true' }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        body: |
          > âŒ Failure, check failure [logs](${{ steps.vars.outputs.run-url }}) below

          Output:
          ```
          ${{ steps.read_output.outputs.content }} 
          ```
          
          Error: 
          ```
          ${{ steps.read_error.outputs.content }}
          ```

    - name: Edit comment with dry run message
      if: ${{ inputs.send  == 'false' && inputs.from_pr == 'true'}}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        body: |
          > âœ… Dry run success, see output [here](${{ steps.vars.outputs.run-url }})
          > Rerun the command with send=true to publish the TX to the safe
          
          Output:
          ```
          ${{ steps.read_output.outputs.content }}
          ```
      continue-on-error: true

    - name: Set PR url
      if: ${{ inputs.from_pr == 'true' }}
      id: pr-url
      run: |
        echo "::set-output name=pr-url::https://github.com/${{github.repository}}/pull/${{ inputs.pull_request_number }}/files"

    - name: Create Telegram message - from PR
      if: ${{ inputs.send  == 'true' && inputs.from_pr == 'true' }}
      run: |
          TELEGRAM_MESSAGE=$(cat << EOF
          âœï¸ [${{ inputs.network}} #${{ env.NONCE }}](${{ env.SAFE_LINK }}) \`${{ steps.get-pr-title.outputs.result}}\`
          Sender: ${{ steps.get-pr-author.outputs.result }}
          Description: \`${{ steps.get-pr-body.outputs.result }}\`
          Review [the code](${{ steps.pr-url.outputs.pr-url }}), verify [the output](${{ steps.vars.outputs.run-url }}), and [sign here](${{ env.SAFE_LINK }})
          EOF
          )
          echo "TELEGRAM_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "$TELEGRAM_MESSAGE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

    - name: Create Telegram message - automated
      if: ${{ inputs.send  == 'true' && inputs.from_pr == 'false' }}
      run: |
          TELEGRAM_MESSAGE=$(cat << EOF
          âœï¸ [${{ inputs.network}} #${{ env.NONCE }}](${{ env.SAFE_LINK }}) \`${{ steps.get-pr-title.outputs.result}}\`
          Sender: ${{ inputs.job_author }} (via cronjob or manual trigger)
          Description: ${{ inputs.job_description }}
          Function ran: ${{ inputs.fn }} in ${{inputs.file}}.py
          Verify [the output](${{ steps.vars.outputs.run-url }}), and [sign here](${{ env.SAFE_LINK }})
          EOF
          )
          echo "TELEGRAM_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "$TELEGRAM_MESSAGE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

    - name: New TX Telegram Alert - Robowoofy Alert Chat
      if: ${{ inputs.send == 'true' }}
      run: |
        python3 -m multisig_ci send_and_pin_message ${{ secrets.TELEGRAM_TOKEN }} ${{ inputs.announcement_telegram_chat_id }}
      continue-on-error: true

    - name: New TX Telegram Alert - MultiSig Chat
      if: ${{ inputs.send == 'true' }}
      run: |
        python3 -m multisig_ci send_and_pin_message ${{ secrets.TELEGRAM_TOKEN }} ${{ inputs.group_telegram_chat_id }}
      continue-on-error: true

    - name: Edit comment with full run message
      if: ${{ inputs.send  == 'true' && inputs.from_pr == 'true' }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        body: |
          > âœ… TX with nonce ${{ env.NONCE }} successfully sent. Find output logs [here](${{ steps.vars.outputs.run-url }}). 
          > Find your queued TX on the [Gnosis UI](${{ env.SAFE_LINK }})
          >
          > Your PR has been labeled with tag ${{inputs.network}} ${{ env.NONCE }}, which you can find [here](https://github.com/yearn/strategist-ms/labels?q=${{ env.NONCE }}).
          
          Output:
          ```
          ${{ steps.read_output.outputs.content }}         
          ```
      continue-on-error: true

    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ inputs.send  == 'true' && inputs.from_pr == 'true' }}
      with:
        number: ${{ inputs.pull_request_number }}
        github_token: ${{ secrets.PAT }}
        labels: |
          ${{ inputs.network }} #${{ env.NONCE }}
      continue-on-error: true

    - uses: peter-evans/close-pull@v1
      if: ${{ inputs.send  == 'true' && inputs.close_pr == 'true' && inputs.from_pr == 'true' }}
      with:
        pull-request-number: ${{ inputs.pull_request_number }}
        comment: Auto-closing pull request
      continue-on-error: true

    - name: Delete PRs head branches
      if: ${{ inputs.delete-branch-after-send == 'true' && inputs.send  == 'true' && inputs.from_pr == 'true'}}
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ secrets.PAT }}
        numbers: ${{ inputs.pull_request_number }}
      continue-on-error: true

    - name: Add reaction
      if: ${{ inputs.from_pr == 'true' }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ inputs.comment-id }}
        reaction-type: hooray
      continue-on-error: true

    - name: Telegram Alert On Infra Failure
      if: ${{ failure() && steps.failcheck.outcome == 'success' }}
      uses: appleboy/telegram-action@master
      with:
        disable_web_page_preview: true 
        to: ${{ inputs.failure_telegram_chat_id}}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Grrrr grrrrr grrrrr ${{ steps.vars.outputs.run-url }} pipeline failed even though the brownie function succeeded!
      continue-on-error: true

    - name: Telegram Alert On Brownie Timeout
      if: ${{ failure() && steps.timeout.outputs.brownie-timeout == 'true' }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.failure_telegram_chat_id }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Grrrr grrrrr grrrrr ${{ steps.vars.outputs.run-url }} brownie timed out!
      continue-on-error: true

    - name: cleanup files
      if: always()
      run: |
        rm -rf ~/.brownie/accounts
        rm -f ~/alive.signal
      continue-on-error: true
